---
title: "Instacart Data Analysis"
output:
  flexdashboard::flex_dashboard:
    self_contained: true
    theme: cerulean
    toc: true
    toc_depth: 2
    toc_float: true
output_dir: "docs"
---



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Load required libraries
```{r}
library(flexdashboard)
library(plotly)
library(p8105.datasets)
library(dplyr)
```

```{r}
# Load Instacart dataset
instacart_data <- p8105.datasets::instacart 

# Filter or sample data for easier visualization
set.seed(123)
instacart_sample <- instacart_data %>% 
  sample_n(10000)
```

### Scatterplot: Order Time vs. Add to Cart Order

```{r}
scatter_data <- instacart_sample %>% 
  group_by(order_hour_of_day, add_to_cart_order) %>% 
  summarise(count = n())

scatter_plot <- plot_ly(scatter_data, x = ~order_hour_of_day, y = ~add_to_cart_order, 
                        type = 'scatter', mode = 'markers', size = ~count, 
                        marker = list(opacity = 0.6)) %>%
  layout(title = "Scatterplot: Order Time vs. Add to Cart Order",
         xaxis = list(title = "Hour of the Day"),
         yaxis = list(title = "Add to Cart Order"))
scatter_plot
```

```{r}
bar_data <- instacart_sample %>% 
  group_by(department) %>% 
  summarise(count = n()) %>% 
  arrange(desc(count))

bar_plot <- plot_ly(bar_data, x = ~department, y = ~count, 
                    type = 'bar', marker = list(opacity = 0.7)) %>%
  layout(title = "Products Ordered by Department",
         xaxis = list(title = "Department"),
         yaxis = list(title = "Number of Products"))
bar_plot
```

### Box Plot: Days Since Prior Order by Day of the Week

```{r}
box_data <- instacart_sample %>% 
  filter(!is.na(days_since_prior_order)) %>% 
  group_by(order_dow)

box_plot <- plot_ly(box_data, y = ~days_since_prior_order, x = ~factor(order_dow, labels = c("Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday")),
                    type = 'box') %>%
  layout(title = "Days Since Prior Order by Day of the Week",
         xaxis = list(title = "Day of the Week"),
         yaxis = list(title = "Days Since Prior Order"))
box_plot
```


```{r}
line_data <- instacart_sample %>% 
  group_by(order_hour_of_day) %>% 
  summarise(avg_cart_size = mean(add_to_cart_order))

line_plot <- plot_ly(line_data, x = ~order_hour_of_day, y = ~avg_cart_size, 
                     type = 'scatter', mode = 'lines', line = list(width = 2)) %>%
  layout(title = "Average Order Size Over the Hours of the Day",
         xaxis = list(title = "Hour of the Day"),
         yaxis = list(title = "Average Cart Size"))
line_plot
```


### Histogram: Frequency of Orders by Day of the Week

```{r}
hist_data <- instacart_sample %>% 
  group_by(order_dow) %>% 
  summarise(count = n())

hist_plot <- plot_ly(hist_data, x = ~factor(order_dow, labels = c("Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday")), 
                     y = ~count, type = 'bar') %>%
  layout(title = "Frequency of Orders by Day of the Week",
         xaxis = list(title = "Day of the Week"),
         yaxis = list(title = "Number of Orders"))
hist_plot
```


### Pie Chart: Proportion of Products Ordered by Aisle

```{r}
pie_data <- instacart_sample %>% 
  group_by(aisle) %>% 
  summarise(count = n()) %>% 
  arrange(desc(count)) %>% 
  top_n(10)

pie_chart <- plot_ly(pie_data, labels = ~aisle, values = ~count, type = 'pie') %>%
  layout(title = "Proportion of Products Ordered by Top 10 Aisles")
pie_chart
```















